// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (gr *Group) Users(
	ctx context.Context, limit *int, offset *int,
) (*UserList, error) {
	opts := []UserPaginateOption{}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := gr.Edges.totalCount[0][alias]
	if nodes, err := gr.NamedUsers(alias); err == nil || hasTotalCount {
		pager, err := newUserPager(opts, false)
		if err != nil {
			return nil, err
		}
		conn := &UserList{Edges: []*UserEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, nil, nil, nil, nil, false)
		return conn, nil
	}
	return gr.QueryUsers().PaginateLimitOffset(ctx, limit, offset, opts...)
}

func (u *User) Groups(
	ctx context.Context, limit *int, offset *int,
) (*GroupList, error) {
	opts := []GroupPaginateOption{}
	alias := graphql.GetFieldContext(ctx).Field.Alias
	totalCount, hasTotalCount := u.Edges.totalCount[0][alias]
	if nodes, err := u.NamedGroups(alias); err == nil || hasTotalCount {
		pager, err := newGroupPager(opts, false)
		if err != nil {
			return nil, err
		}
		conn := &GroupList{Edges: []*GroupEdge{}, TotalCount: totalCount}
		conn.build(nodes, pager, nil, nil, nil, nil, false)
		return conn, nil
	}
	return u.QueryGroups().PaginateLimitOffset(ctx, limit, offset, opts...)
}
